version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: innovatech_db
    restart: always
    environment:
      POSTGRES_USER: innovatech_user
      POSTGRES_PASSWORD: InnovaSecurePassword2026!
      POSTGRES_DB: innovatech_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - innovatech_network


  backend1:
    build:
      context: ../backend-1 
      dockerfile: Dockerfile
    container_name: innovatech_backend_1
    restart: always
    environment:
      - DATABASE_URL=postgresql://innovatech_user:InnovaSecurePassword2026!@db:5432/innovatech_prod
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - innovatech_network

  backend2:
    build:
      context: ../backend-2 
      dockerfile: Dockerfile
    container_name: innovatech_backend_2
    restart: always
    environment:
      - DATABASE_URL=postgresql://innovatech_user:InnovaSecurePassword2026!@db:5432/innovatech_prod
      - PORT=8001 
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - innovatech_network

  frontend:
    build:
      context: ../frontend  
      dockerfile: Dockerfile
    container_name: innovatech_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
    networks:
      - innovatech_network

networks:
  innovatech_network:
    driver: bridge

volumes:
  postgres_data:
    name: innovatech_postgres_volumes